import { TalentMagnet } from "./types";

export const magnets: TalentMagnet[] = [
  {
    name: "Sara Morales",
    role: "SVP, People & Communities",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face",
    accelerate: 3, nurture: 2, monitor: 0,
    magnetScore: 96,
    insight: "Strongest magnet — diverse paths, consistent outcomes. Three different career archetypes all developing Accelerate-tier profiles under the same manager.",
    category: "standout",
    totalDeveloped: 14, activeCurrent: 5, internalAlumni: 6, departed: 3, yearsOfInfluence: 8,
    timelineData: [
      { year: 2019, entered: 2, promoted: 0 },
      { year: 2020, entered: 3, promoted: 1 },
      { year: 2021, entered: 2, promoted: 2 },
      { year: 2022, entered: 3, promoted: 1 },
      { year: 2023, entered: 2, promoted: 3 },
      { year: 2024, entered: 2, promoted: 1 },
    ],
    directReports: [
      { name: "Jen Scherler-Gormley", tier: "accelerate", evidence: "Led Splunk integration across 36 countries; sponsorship from EVP and multiple SVPs over a decade", status: "current" },
      { name: "Barry Wiley II", tier: "accelerate", evidence: "Bold pivot from services sales into P&C; recognized by five SVP-level leaders; CMO stated he is 'working at the VP level'", status: "current" },
      { name: "Anh Thu Inman", tier: "accelerate", evidence: "IC to Senior Director in ~3.5 years — one of the fastest trajectories in the dataset", status: "current" },
      { name: "Dr. LaTricia Frederick", tier: "nurture", evidence: "Stepped up to maintain SLT momentum during a leadership transition; owns the DIP Portal and Workforce Scenario Model", status: "current" },
      { name: "Stephen Powell", tier: "nurture", evidence: "SVP and EVP recognition spanning nearly a decade; driving P&C transformation change management", status: "current" },
      { name: "Marcus Chen", tier: "accelerate", evidence: "Promoted to VP at partner firm after 3 years under Sara; now leads global HR for a Fortune 200", status: "departed" },
      { name: "Priya Sharma", tier: "nurture", evidence: "Moved to SVP role in another BU; credits Sara's mentorship for cross-functional leadership skills", status: "alumni" },
    ],
  },
  {
    name: "Megan Bazan",
    role: "VP, People & Communities",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
    accelerate: 1, nurture: 7, monitor: 0,
    magnetScore: 91,
    insight: "Deepest bench — several near breakthrough. Eight directors showing meaningful VP potential with zero Monitor-tier leaders.",
    category: "standout",
    totalDeveloped: 12, activeCurrent: 8, internalAlumni: 3, departed: 1, yearsOfInfluence: 6,
    timelineData: [
      { year: 2019, entered: 1, promoted: 0 },
      { year: 2020, entered: 2, promoted: 0 },
      { year: 2021, entered: 3, promoted: 1 },
      { year: 2022, entered: 2, promoted: 1 },
      { year: 2023, entered: 2, promoted: 2 },
      { year: 2024, entered: 2, promoted: 1 },
    ],
    directReports: [
      { name: "Maddie Underwood", tier: "nurture", evidence: "Recognition from the CEO (twice), multiple EVPs and SVPs across unrelated functions — rare breadth of trust", status: "current" },
      { name: "Mandy Sullivan", tier: "nurture", evidence: "IC to Director in ~28 months; called a 'thought leader, consultant, and connector' by an SVP", status: "current" },
    ],
  },
  {
    name: "Chris Dexter",
    role: "VP, Engineering",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    accelerate: 2, nurture: 3, monitor: 0,
    magnetScore: 85,
    insight: "Quality over quantity in engineering. Shows that engineering leaders can build cross-enterprise visibility with deliberate program-level ownership.",
    category: "strong",
    totalDeveloped: 9, activeCurrent: 5, internalAlumni: 3, departed: 1, yearsOfInfluence: 7,
    timelineData: [
      { year: 2019, entered: 1, promoted: 0 },
      { year: 2020, entered: 1, promoted: 1 },
      { year: 2021, entered: 2, promoted: 0 },
      { year: 2022, entered: 1, promoted: 1 },
      { year: 2023, entered: 2, promoted: 1 },
      { year: 2024, entered: 2, promoted: 1 },
    ],
    directReports: [
      { name: "Ullie Versavel", tier: "accelerate", evidence: "Overcame 14-year plateau to earn Pinnacle Award and three international Stevie Awards; EVP/COO recognition", status: "current" },
      { name: "Ram Jayaram", tier: "accelerate", evidence: "Drove the Omega licensing transformation; COO-level recognition as an ONExcellence finalist", status: "current" },
    ],
  },
  {
    name: "Heather Dickinson",
    role: "VP, Corporate Communications",
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face",
    accelerate: 2, nurture: 2, monitor: 0,
    magnetScore: 82,
    insight: "Exceptional talent, structural path question. Both Accelerate leaders are VP+ caliber but path depends on functional head role opening.",
    category: "strong",
    totalDeveloped: 7, activeCurrent: 4, internalAlumni: 2, departed: 1, yearsOfInfluence: 5,
    timelineData: [
      { year: 2020, entered: 1, promoted: 0 },
      { year: 2021, entered: 2, promoted: 1 },
      { year: 2022, entered: 1, promoted: 0 },
      { year: 2023, entered: 2, promoted: 1 },
      { year: 2024, entered: 1, promoted: 1 },
    ],
    directReports: [
      { name: "Robyn Blum", tier: "accelerate", evidence: "Over $33,000 in recognition from the CEO alone; described as the leader 'at the helm' of business-critical communications", status: "current" },
      { name: "Meredith Corley", tier: "accelerate", evidence: "Nine separate recognitions from EVP Jeetu Patel; led communications through Ukraine crisis and Log4j", status: "current" },
    ],
  },
  {
    name: "Brian Tippens",
    role: "SVP, People & Communities",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    accelerate: 1, nurture: 6, monitor: 0,
    magnetScore: 80,
    insight: "Strong talent, domain-breadth question. Recurring question is whether specialized domains (CSR, DEI) offer a clear path to VP+ scope.",
    category: "strong",
    totalDeveloped: 10, activeCurrent: 7, internalAlumni: 2, departed: 1, yearsOfInfluence: 6,
    timelineData: [
      { year: 2019, entered: 2, promoted: 0 },
      { year: 2020, entered: 1, promoted: 1 },
      { year: 2021, entered: 2, promoted: 0 },
      { year: 2022, entered: 2, promoted: 1 },
      { year: 2023, entered: 2, promoted: 1 },
      { year: 2024, entered: 1, promoted: 0 },
    ],
    directReports: [
      { name: "Taryn Petryk", tier: "nurture", evidence: "Led the DEI organization on an interim basis; orchestrated enterprise-wide Executive Orders response across 112 meetings", status: "current" },
    ],
  },
  {
    name: "Ty Thorsen",
    role: "SVP, Engineering",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    accelerate: 1, nurture: 6, monitor: 0,
    magnetScore: 78,
    insight: "Solid pipeline, uneven readiness. Strong bench depth but leaders are at varying stages of development.",
    category: "strong",
    totalDeveloped: 11, activeCurrent: 7, internalAlumni: 3, departed: 1, yearsOfInfluence: 7,
    timelineData: [
      { year: 2019, entered: 1, promoted: 0 },
      { year: 2020, entered: 2, promoted: 0 },
      { year: 2021, entered: 2, promoted: 1 },
      { year: 2022, entered: 2, promoted: 1 },
      { year: 2023, entered: 2, promoted: 1 },
      { year: 2024, entered: 2, promoted: 0 },
    ],
    directReports: [],
  },
  {
    name: "Surbhi Kaul",
    role: "VP, CX Product Management",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&h=200&fit=crop&crop=face",
    accelerate: 0, nurture: 5, monitor: 5,
    magnetScore: 38,
    insight: "Organizational design issue — momentum fades. Five leaders show the same peaked-and-faded arc, raising structural questions about sustained development.",
    category: "gap",
    totalDeveloped: 10, activeCurrent: 10, internalAlumni: 0, departed: 0, yearsOfInfluence: 4,
    timelineData: [
      { year: 2021, entered: 3, promoted: 0 },
      { year: 2022, entered: 3, promoted: 0 },
      { year: 2023, entered: 2, promoted: 0 },
      { year: 2024, entered: 2, promoted: 0 },
    ],
    directReports: [
      { name: "Hope Ferguson", tier: "monitor", evidence: "Went from EVP recognition for CX P&L Transformation → $100 awards for 'helping with comm items'", status: "current" },
      { name: "Matt Lewis", tier: "monitor", evidence: "Went from 'ground-breaking product management work' → modest peer recognition for shift coverage", status: "current" },
    ],
  },
  {
    name: "Gary Hall",
    role: "VP, Sales Strategy & Planning",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face",
    accelerate: 0, nurture: 1, monitor: 5,
    magnetScore: 22,
    insight: "Role design issue — support vs. leadership. Sales Strategy may be structured where dominant work product is operational enablement, not transformation ownership.",
    category: "gap",
    totalDeveloped: 8, activeCurrent: 6, internalAlumni: 1, departed: 1, yearsOfInfluence: 5,
    timelineData: [
      { year: 2020, entered: 2, promoted: 0 },
      { year: 2021, entered: 2, promoted: 0 },
      { year: 2022, entered: 1, promoted: 0 },
      { year: 2023, entered: 2, promoted: 0 },
      { year: 2024, entered: 1, promoted: 0 },
    ],
    directReports: [
      { name: "Virginia Wallen", tier: "monitor", evidence: "Over $16,000 from SVPs but entirely for logistics — 'amazing GSX event,' 'well coordinated events'", status: "current" },
    ],
  },
  {
    name: "Neerka Tandon",
    role: "Director, Software Engineering",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
    accelerate: 0, nurture: 2, monitor: 5,
    magnetScore: 25,
    insight: "Altitude ceiling — needs external visibility. A Director managing Directors creates a structural ceiling where leaders lack SVP/VP-level recognition.",
    category: "gap",
    totalDeveloped: 7, activeCurrent: 7, internalAlumni: 0, departed: 0, yearsOfInfluence: 3,
    timelineData: [
      { year: 2022, entered: 3, promoted: 0 },
      { year: 2023, entered: 2, promoted: 0 },
      { year: 2024, entered: 2, promoted: 0 },
    ],
    directReports: [],
  },
];
